### ISSUE TITLE
rip this mod

### ISSUE THREAD

**Issue by braainsiogame** [Quezler/iknowwhatimdoing#1]
![image](https://user-images.githubusercontent.com/59963353/82543356-9caca980-9b7d-11ea-936a-b4b8413ab753.png)

**Comment by Quezler** [comment]
![cover2](https://user-images.githubusercontent.com/3179271/82544067-d61cef00-9b54-11ea-9957-2b1773633927.jpg)

**Comment by Quezler** [comment]
countermanded. 📜

**Comment by braainsiogame** [comment]
no

**Comment by Quezler** [comment]
tchaikovsky yes

**Comment by braainsiogame** [comment]
no

**Comment by Quezler** [comment]
tchaikovsky always yes

**Comment by braainsiogame** [comment]
No

**Comment by Quezler** [comment]
jawhöl

**Comment by braainsiogame** [comment]
no

**Comment by Quezler** [comment]
![index](https://user-images.githubusercontent.com/3179271/83229164-c66e5d80-a187-11ea-9ef0-bf2a1f164f5e.jpg)

**Comment by braainsiogame** [comment]
no

**Comment by Quezler** [comment]
!no

**Comment by braainsiogame** [comment]
no
